<?php
function getStartPosition(){
    return [
        "a1" => "wr",
        "b1" => "wn",
        "c1" => "wb",
        "d1" => "wq",
        "e1" => "wk",
        "f1" => "wb",
        "g1" => "wn",
        "h1" => "wr",
        "a2" => "wp",
        "b2" => "wp",
        "c2" => "wp",
        "d2" => "wp",
        "e2" => "wp",
        "f2" => "wp",
        "g2" => "wp",
        "h2" => "wp",
        "a7" => "zp",
        "b7" => "zp",
        "c7" => "zp",
        "d7" => "zp",
        "e7" => "zp",
        "f7" => "zp",
        "g7" => "zp",
        "h7" => "zp",
        "a8" => "zr",
        "b8" => "zn",
        "c8" => "zb",
        "d8" => "zq",
        "e8" => "zk",
        "f8" => "zb",
        "g8" => "zn",
        "h8" => "zr"
        ];    
}
